[2023-02-27T20:29:28.777+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2023-02-27T20:29:26.425795+00:00 [queued]>
[2023-02-27T20:29:28.802+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2023-02-27T20:29:26.425795+00:00 [queued]>
[2023-02-27T20:29:28.802+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:29:28.802+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T20:29:28.803+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:29:28.834+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2023-02-27 20:29:26.425795+00:00
[2023-02-27T20:29:28.839+0000] {standard_task_runner.py:55} INFO - Started process 98 to run task
[2023-02-27T20:29:28.842+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'manual__2023-02-27T20:29:26.425795+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmp9fi3x1bg']
[2023-02-27T20:29:28.843+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_pet_table
[2023-02-27T20:29:29.053+0000] {task_command.py:388} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table manual__2023-02-27T20:29:26.425795+00:00 [running]> on host 0fe5beb48994
[2023-02-27T20:29:29.271+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T20:29:26.425795+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T20:29:26.425795+00:00
[2023-02-27T20:29:29.271+0000] {sql.py:254} INFO - Executing: -- create pet table
CREATE TABLE IF NOT EXISTS pet (
    pet_id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    pet_type VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    OWNER VARCHAR NOT NULL);
[2023-02-27T20:29:29.319+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-27T20:29:29.351+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20230227T202926, start_date=20230227T202928, end_date=20230227T202929
[2023-02-27T20:29:29.399+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_pet_table (The conn_id `postgres_default` isn't defined; 98)
[2023-02-27T20:29:29.421+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T20:29:29.462+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
