[2023-02-27T20:07:02.631+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:07:02.667+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:07:02.668+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:07:02.678+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T20:07:02.678+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:07:02.723+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2020-02-02 00:00:00+00:00
[2023-02-27T20:07:02.728+0000] {standard_task_runner.py:55} INFO - Started process 996 to run task
[2023-02-27T20:07:02.731+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'scheduled__2020-02-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmpyhwfjr1i']
[2023-02-27T20:07:02.739+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_pet_table
[2023-02-27T20:07:02.919+0000] {task_command.py:388} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [running]> on host ecae85519c84
[2023-02-27T20:07:03.127+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T00:00:00+00:00
[2023-02-27T20:07:03.129+0000] {sql.py:254} INFO - Executing: -- create pet table
CREATE TABLE IF NOT EXISTS pet (
    pet_id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    pet_type VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    OWNER VARCHAR NOT NULL);
[2023-02-27T20:07:03.203+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-27T20:07:03.241+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20200202T000000, start_date=20230227T200702, end_date=20230227T200703
[2023-02-27T20:07:03.304+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_pet_table (The conn_id `postgres_default` isn't defined; 996)
[2023-02-27T20:07:03.330+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T20:07:03.368+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-27T20:11:34.352+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:11:34.376+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:11:34.376+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:11:34.376+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T20:11:34.376+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:11:34.401+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2020-02-02 00:00:00+00:00
[2023-02-27T20:11:34.460+0000] {standard_task_runner.py:55} INFO - Started process 154 to run task
[2023-02-27T20:11:34.468+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'scheduled__2020-02-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmpkjh6cqd9']
[2023-02-27T20:11:34.468+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_pet_table
[2023-02-27T20:11:34.627+0000] {task_command.py:388} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [running]> on host 9b706fb5cfff
[2023-02-27T20:11:34.725+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T00:00:00+00:00
[2023-02-27T20:11:34.727+0000] {sql.py:254} INFO - Executing: -- create pet table
CREATE TABLE IF NOT EXISTS pet (
    pet_id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    pet_type VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    OWNER VARCHAR NOT NULL);
[2023-02-27T20:11:34.746+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-27T20:11:34.755+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20200202T000000, start_date=20230227T201134, end_date=20230227T201134
[2023-02-27T20:11:34.775+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_pet_table (The conn_id `postgres_default` isn't defined; 154)
[2023-02-27T20:11:34.807+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T20:11:34.842+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-27T20:17:49.670+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:17:49.690+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:17:49.691+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:17:49.691+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T20:17:49.691+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:17:49.719+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2020-02-02 00:00:00+00:00
[2023-02-27T20:17:49.731+0000] {standard_task_runner.py:55} INFO - Started process 128 to run task
[2023-02-27T20:17:49.734+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'scheduled__2020-02-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmp9jyz8pcf']
[2023-02-27T20:17:49.735+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_pet_table
[2023-02-27T20:17:49.885+0000] {task_command.py:388} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [running]> on host 9a54fb355ce5
[2023-02-27T20:17:50.054+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T00:00:00+00:00
[2023-02-27T20:17:50.055+0000] {sql.py:254} INFO - Executing: -- create pet table
CREATE TABLE IF NOT EXISTS pet (
    pet_id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    pet_type VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    OWNER VARCHAR NOT NULL);
[2023-02-27T20:17:50.075+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-27T20:17:50.086+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20200202T000000, start_date=20230227T201749, end_date=20230227T201750
[2023-02-27T20:17:50.108+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_pet_table (The conn_id `postgres_default` isn't defined; 128)
[2023-02-27T20:17:50.149+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T20:17:50.262+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-27T20:29:28.780+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:29:28.802+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-02-27T20:29:28.802+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:29:28.802+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T20:29:28.803+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T20:29:28.891+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2020-02-02 00:00:00+00:00
[2023-02-27T20:29:28.898+0000] {standard_task_runner.py:55} INFO - Started process 99 to run task
[2023-02-27T20:29:28.905+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'scheduled__2020-02-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmp1jq5b65t']
[2023-02-27T20:29:28.906+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_pet_table
[2023-02-27T20:29:29.084+0000] {task_command.py:388} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [running]> on host 0fe5beb48994
[2023-02-27T20:29:29.282+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T00:00:00+00:00
[2023-02-27T20:29:29.283+0000] {sql.py:254} INFO - Executing: -- create pet table
CREATE TABLE IF NOT EXISTS pet (
    pet_id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    pet_type VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    OWNER VARCHAR NOT NULL);
[2023-02-27T20:29:29.333+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-27T20:29:29.349+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20200202T000000, start_date=20230227T202928, end_date=20230227T202929
[2023-02-27T20:29:29.399+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_pet_table (The conn_id `postgres_default` isn't defined; 99)
[2023-02-27T20:29:29.427+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T20:29:29.445+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
